version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart : unless-stopped
    volumes:
      - /home/mysqldata:/var/lib/mysql
  service_app:
    image : tpachat
    container_name:  tpachat
    restart: on-failure
    ports:
      - 9090:9090
    depends_on:
      - mysqldb